"use strict";
/* Data comes from data.js (generated by build.ps1 from the ../JLPT_Nx_Reviewer.md files). */

/* ================= config & state ================= */
const LEVELS = ["N5","N4","N3","N2","N1"];
const LEVEL_COLORS = {N5:"#10b981",N4:"#0ea5e9",N3:"#6366f1",N2:"#a855f7",N1:"#ef4444"};
const DECKS = [
  {id:"kanji", label:"漢字読み", sub:"Kanji → reading"},
  {id:"para",  label:"言い換え", sub:"Paraphrase"}
];
const store = {
  get(k,d){ try{ const v = localStorage.getItem(k); return v===null?d:JSON.parse(v); }catch(e){ return d; } },
  set(k,v){ try{ localStorage.setItem(k, JSON.stringify(v)); }catch(e){} }
};
const state = {
  level: store.get("jlpt.level","N5"),
  view:  store.get("jlpt.view","review"),
  deck:  store.get("jlpt.deck","kanji"),
  order: [], pos:0, flipped:false, confirmReset:false, hideKnown:false,
  quiz:null
};
if(!LEVELS.includes(state.level)) state.level = "N5";

/* ================= md parsing ================= */
function escapeHtml(s){
  return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
}
function inline(s){
  return escapeHtml(s)
    .replace(/\*\*(.+?)\*\*/g,"<b>$1</b>")
    .replace(/(^|[^*])\*([^*\s][^*]*)\*(?!\*)/g,"$1<i>$2</i>")
    .replace(/★/g,'<span class="star">★</span>');
}
function renderBlock(lines){
  const out=[]; let i=0;
  const isTable = l => /^\s*\|/.test(l);
  const isUl = l => /^\s*-\s+/.test(l);
  const isOl = l => /^\s*\d+\.\s+/.test(l);
  while(i<lines.length){
    const line = lines[i];
    if(!line.trim()){ i++; continue; }
    if(line.startsWith("#### ")){ out.push("<h4>"+inline(line.slice(5))+"</h4>"); i++; continue; }
    if(line.startsWith("### ")){ out.push("<h3>"+inline(line.slice(4))+"</h3>"); i++; continue; }
    if(/^-{3,}\s*$/.test(line.trim())){ out.push("<hr>"); i++; continue; }
    if(isTable(line)){
      const rows=[];
      while(i<lines.length && isTable(lines[i])){ rows.push(lines[i]); i++; }
      const cells = r => r.trim().replace(/^\|/,"").replace(/\|$/,"").split("|").map(c=>inline(c.trim()));
      let html='<div class="table-wrap"><table>';
      rows.forEach((r,ri)=>{
        if(/^[\s|:\-]+$/.test(r)) return;
        const tag = ri===0 ? "th" : "td";
        html += "<tr>"+cells(r).map(c=>`<${tag}>${c}</${tag}>`).join("")+"</tr>";
      });
      out.push(html+"</table></div>");
      continue;
    }
    if(isUl(line)){
      const items=[];
      while(i<lines.length && isUl(lines[i])){ items.push(lines[i].replace(/^\s*-\s+/,"")); i++; }
      out.push("<ul>"+items.map(t=>"<li>"+inline(t)+"</li>").join("")+"</ul>");
      continue;
    }
    if(isOl(line)){
      const items=[];
      while(i<lines.length && isOl(lines[i])){ items.push(lines[i].replace(/^\s*\d+\.\s+/,"")); i++; }
      out.push("<ol>"+items.map(t=>"<li>"+inline(t)+"</li>").join("")+"</ol>");
      continue;
    }
    out.push("<p>"+inline(line)+"</p>"); i++;
  }
  return out.join("\n");
}
function sectionEmoji(title){
  if(/文法|Grammar/i.test(title)) return "📖";
  if(/語彙|Vocab/i.test(title)) return "✏️";
  if(/読解|Reading/i.test(title)) return "📚";
  if(/Scoring|Game/i.test(title)) return "🎯";
  if(/48/i.test(title)) return "⏰";
  if(/Plan|Month|Sitting|Away/i.test(title)) return "🗓️";
  return "📌";
}
function parseLevel(lv){
  const md = JLPT_MD[lv] || "";
  const lines = md.split(/\r?\n/);
  let title="", intro=[], sections=[], cur=null;
  for(const line of lines){
    if(!title && line.startsWith("# ")){ title=line.slice(2).trim(); continue; }
    if(line.startsWith("## ")){ cur={title:line.slice(3).trim(), lines:[]}; sections.push(cur); continue; }
    if(cur) cur.lines.push(line);
    else if(line.trim() && !/^-{3,}$/.test(line.trim())) intro.push(line.trim());
  }
  /* kanji cards: 漢字(よみ — meaning) — meaning part optional */
  const kanji=[]; const seen=new Set();
  const re=/([々一-鿿]+[ぁ-ゖ]{0,5})\(([ぁ-ゖー]+(?:[\/・][ぁ-ゖー]+)*)(?:\s*—\s*([^)]+))?\)/g;
  let m;
  while((m=re.exec(md))!==null){
    const key=m[1]+"|"+m[2];
    if(m[1].length>8 || seen.has(key)) continue;
    seen.add(key); kanji.push({f:m[1], b:m[2], m:(m[3]||"").trim()});
  }
  /* paraphrase cards: A ≒ B (gloss) — gloss optional */
  const para=[]; const seenP=new Set();
  for(const raw of lines){
    if(!raw.includes("≒")) continue;
    const body=raw.replace(/^\s*-\s+/,"");
    for(const chunk of body.split(" / ")){
      if(!chunk.includes("≒")) continue;
      let [f,b]=chunk.split("≒").map(s=>s.trim());
      if(!f||!b) continue;
      let gloss="";
      const g=b.match(/^(.*?)\s*\(([^)]*[A-Za-z][^)]*)\)$/);
      if(g){ b=g[1].trim(); gloss=g[2].trim(); }
      if(f.length>25||b.length>30) continue;
      const key=f+"|"+b;
      if(seenP.has(key)) continue;
      seenP.add(key); para.push({f,b,m:gloss});
    }
  }
  return {title, intro:intro.join(" "), sections, kanji, para};
}
const PARSED={};
for(const lv of LEVELS) PARSED[lv]=parseLevel(lv);

/* ================= helpers ================= */
const $=s=>document.querySelector(s);
function shuffle(a){ const x=a.slice(); for(let i=x.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [x[i],x[j]]=[x[j],x[i]]; } return x; }
function deckCards(){ const p=PARSED[state.level]; return state.deck==="kanji"?p.kanji:p.para; }
function knownKey(){ return `jlpt.known.${state.level}.${state.deck}`; }
function getKnown(){ return new Set(store.get(knownKey(),[])); }
function setKnown(set){ store.set(knownKey(),[...set]); }
function deckLabel(){ return DECKS.find(d=>d.id===state.deck).label; }

/* ================= header ================= */
function renderHeader(){
  $("#levelBar").innerHTML = LEVELS.map(lv=>
    `<button class="lv ${lv===state.level?"active":""}" style="--lvcolor:${LEVEL_COLORS[lv]}" data-lv="${lv}">${lv}</button>`
  ).join("");
  document.querySelectorAll("#levelBar .lv").forEach(b=>b.onclick=()=>{
    state.level=b.dataset.lv; store.set("jlpt.level",state.level);
    document.documentElement.style.setProperty("--accent",LEVEL_COLORS[state.level]);
    document.documentElement.style.setProperty("--accent-soft",LEVEL_COLORS[state.level]+"22");
    state.confirmReset=false; state.quiz=null;
    renderHeader(); renderView();
  });
  const tabs=[["review","📖 Review"],["cards","🎴 Cards"],["quiz","✅ Quiz"]];
  $("#tabBar").innerHTML = tabs.map(([id,label])=>
    `<button class="tab ${id===state.view?"active":""}" data-v="${id}">${label}</button>`
  ).join("");
  document.querySelectorAll("#tabBar .tab").forEach(b=>b.onclick=()=>{
    state.view=b.dataset.v; store.set("jlpt.view",state.view);
    state.confirmReset=false;
    renderHeader(); renderView();
  });
}

/* ================= review view ================= */
let reviewQuery="";
function sectionCard(sec, open){
  const d=document.createElement("details");
  d.className="sec";
  if(open) d.open=true;
  d.innerHTML=`<summary><span>${sectionEmoji(sec.title)}</span><span>${inline(sec.title)}</span><span class="chev">▸</span></summary>
    <div class="sec-body">${renderBlock(sec.lines)}</div>`;
  return d;
}
function fillSectionList(){
  const p=PARSED[state.level];
  const list=$("#secList");
  const q=reviewQuery.trim().toLowerCase();
  $("#searchClear").hidden=!reviewQuery;
  list.innerHTML="";
  let shown=0;
  p.sections.forEach((sec,idx)=>{
    const text=(sec.title+"\n"+sec.lines.join("\n")).toLowerCase();
    if(q && !text.includes(q)) return;
    shown++;
    list.appendChild(sectionCard(sec, q||idx===0));
  });
  if(!shown) list.innerHTML=`<div class="noresult">No sections match “${escapeHtml(reviewQuery)}”</div>`;
  if(q) highlight(list,q);
}
function renderReview(){
  const p=PARSED[state.level];
  const host=$("#view-review");
  host.innerHTML=`
    <div class="pagehead"><h1>${inline(p.title)}</h1><p>${inline(p.intro)}</p></div>
    <div id="searchWrap">
      <input id="searchBox" type="search" placeholder="Search this reviewer… (e.g. ばかりに, counters)" value="${escapeHtml(reviewQuery)}" autocomplete="off">
      <button id="searchClear" ${reviewQuery?"":"hidden"}>✕</button>
    </div>
    <div id="secList"></div>`;
  fillSectionList();
  const box=$("#searchBox");
  box.oninput=()=>{ reviewQuery=box.value; fillSectionList(); };
  $("#searchClear").onclick=()=>{ reviewQuery=""; renderReview(); $("#searchBox").focus(); };
}
function highlight(root,q){
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
  const targets=[];
  while(walker.nextNode()){
    const n=walker.currentNode;
    if(n.nodeValue.toLowerCase().includes(q)) targets.push(n);
  }
  for(const n of targets){
    const frag=document.createDocumentFragment();
    let text=n.nodeValue, lower=text.toLowerCase(), pos=0, idx;
    while((idx=lower.indexOf(q,pos))!==-1){
      frag.appendChild(document.createTextNode(text.slice(pos,idx)));
      const mk=document.createElement("mark");
      mk.textContent=text.slice(idx,idx+q.length);
      frag.appendChild(mk);
      pos=idx+q.length;
    }
    frag.appendChild(document.createTextNode(text.slice(pos)));
    n.parentNode.replaceChild(frag,n);
  }
}

/* ================= cards view ================= */
function buildOrder(){
  const known=getKnown();
  let idxs=deckCards().map((_,i)=>i);
  if(state.hideKnown) idxs=idxs.filter(i=>!known.has(deckCards()[i].f));
  state.order=shuffle(idxs); state.pos=0; state.flipped=false;
}
function renderDeckRow(){
  return DECKS.map(d=>{
    const n=PARSED[state.level][d.id==="kanji"?"kanji":"para"].length;
    return `<button class="deckbtn ${d.id===state.deck?"active":""}" data-d="${d.id}">${d.label}<small>${d.sub} · ${n} cards</small></button>`;
  }).join("");
}
function renderCards(){
  const host=$("#view-cards");
  const cards=deckCards();
  const known=getKnown();
  if(state.order.length===0 && cards.length) buildOrder();
  if(state.order.some(i=>i>=cards.length)) buildOrder();
  const done = state.pos>=state.order.length;
  const card = done?null:cards[state.order[state.pos]];
  const pct = cards.length?Math.round(known.size/cards.length*100):0;
  host.innerHTML=`
    <div class="deckrow">${renderDeckRow()}</div>
    <div class="panel">
      <div class="meta"><span>Mastered ${known.size}/${cards.length}</span><span>${pct}%</span></div>
      <div class="progress"><div style="width:${pct}%"></div></div>
      ${cards.length===0?`<p class="subnote">No cards found for this deck at ${state.level}.</p>`:
      done?`
        <div class="donebox">
          <div class="big">🎉</div>
          <p><b>Deck finished!</b><br><span class="subnote">${known.size} of ${cards.length} marked as mastered.</span></p>
          <div class="toolrow"><button class="ghost" id="restartBtn">🔁 Go again</button></div>
        </div>`:`
        <div class="fc ${state.flipped?"flipped":""}" id="fcard">
          <div class="fc-inner">
            <div class="fc-face">
              <span class="fc-tag">${deckLabel()} · ${state.pos+1}/${state.order.length}</span>
              <div class="fc-word">${escapeHtml(card.f)}</div>
              <div class="fc-hint">tap to reveal</div>
            </div>
            <div class="fc-face fc-back">
              <span class="fc-tag">${state.deck==="kanji"?"READING":"MEANING"}</span>
              <div class="fc-word" style="color:var(--accent)">${escapeHtml(card.b)}</div>
              ${card.m?`<div class="fc-mean">${escapeHtml(card.m)}</div>`:""}
              <div class="fc-hint">${escapeHtml(card.f)}</div>
            </div>
          </div>
        </div>
        <div class="btnrow">
          <button class="abtn again" id="againBtn">↻ Again</button>
          <button class="abtn know" id="knowBtn">✓ Got it</button>
        </div>`}
      <label class="checklabel"><input type="checkbox" id="hideKnown" ${state.hideKnown?"checked":""}> Skip mastered cards</label>
      <div class="toolrow">
        <button class="ghost" id="shuffleBtn">🔀 Reshuffle</button>
        <button class="ghost ${state.confirmReset?"warn":""}" id="resetBtn">${state.confirmReset?"Tap again to confirm reset":"♻️ Reset progress"}</button>
      </div>
    </div>`;
  document.querySelectorAll("#view-cards .deckbtn").forEach(b=>b.onclick=()=>{
    state.deck=b.dataset.d; store.set("jlpt.deck",state.deck);
    state.order=[]; state.confirmReset=false; renderCards();
  });
  const fc=$("#fcard");
  if(fc) fc.onclick=()=>{ state.flipped=!state.flipped; fc.classList.toggle("flipped",state.flipped); };
  const knowBtn=$("#knowBtn");
  if(knowBtn) knowBtn.onclick=()=>{
    const k=getKnown(); k.add(cards[state.order[state.pos]].f); setKnown(k);
    state.pos++; state.flipped=false; renderCards();
  };
  const againBtn=$("#againBtn");
  if(againBtn) againBtn.onclick=()=>{
    state.order.push(state.order[state.pos]);   /* recycle to the end */
    state.pos++; state.flipped=false; renderCards();
  };
  const restart=$("#restartBtn");
  if(restart) restart.onclick=()=>{ buildOrder(); renderCards(); };
  $("#shuffleBtn").onclick=()=>{ buildOrder(); renderCards(); };
  $("#hideKnown").onchange=e=>{ state.hideKnown=e.target.checked; buildOrder(); renderCards(); };
  $("#resetBtn").onclick=()=>{
    if(!state.confirmReset){ state.confirmReset=true; renderCards(); return; }
    setKnown(new Set()); state.confirmReset=false; buildOrder(); renderCards();
  };
}

/* ================= quiz view ================= */
function bestKey(){ return `jlpt.best.${state.level}.${state.deck}`; }
function startQuiz(){
  const pool=deckCards();
  const qs=shuffle(pool).slice(0,Math.min(10,pool.length)).map(card=>{
    const wrong=shuffle(pool.filter(c=>c.b!==card.b)).slice(0,3).map(c=>c.b);
    return {card, opts:shuffle([card.b,...wrong])};
  });
  state.quiz={qs,i:0,score:0,picked:null,finished:false};
}
function renderQuiz(){
  const host=$("#view-quiz");
  const pool=deckCards();
  const best=store.get(bestKey(),null);
  if(!state.quiz){
    host.innerHTML=`
      <div class="deckrow">${renderDeckRow()}</div>
      <div class="panel">
        <h1 style="font-size:1.1rem;margin:0 0 6px">${deckLabel()} Quiz — ${state.level}</h1>
        <p class="subnote" style="text-align:left">10 multiple-choice questions drawn from the ${pool.length} ${deckLabel()} items in the ${state.level} reviewer.${best!==null?` Best score: <b>${best}/10</b>.`:""}</p>
        ${pool.length<4?`<p class="subnote">Not enough items in this deck to build a quiz.</p>`:
        `<button class="startbtn" id="startQuiz">▶ Start quiz</button>`}
      </div>`;
    document.querySelectorAll("#view-quiz .deckbtn").forEach(b=>b.onclick=()=>{
      state.deck=b.dataset.d; store.set("jlpt.deck",state.deck); renderQuiz();
    });
    const sb=$("#startQuiz");
    if(sb) sb.onclick=()=>{ startQuiz(); renderQuiz(); };
    return;
  }
  const qz=state.quiz;
  if(qz.finished){
    const prevBest=store.get(bestKey(),0);
    const newBest=Math.max(prevBest,qz.score);
    store.set(bestKey(),newBest);
    const emoji=qz.score>=9?"🏆":qz.score>=7?"🎉":qz.score>=5?"💪":"📚";
    host.innerHTML=`
      <div class="panel">
        <div class="donebox">
          <div class="big">${emoji}</div>
          <div class="scorebig">${qz.score}/${qz.qs.length}</div>
          <p class="subnote">${deckLabel()} · ${state.level} · Best: ${newBest}/10</p>
          <div class="toolrow">
            <button class="startbtn" id="retryQuiz" style="max-width:220px">↻ Try again</button>
            <button class="ghost" id="quizBack">Choose deck</button>
          </div>
        </div>
      </div>`;
    $("#retryQuiz").onclick=()=>{ startQuiz(); renderQuiz(); };
    $("#quizBack").onclick=()=>{ state.quiz=null; renderQuiz(); };
    return;
  }
  const q=qz.qs[qz.i];
  const answered=qz.picked!==null;
  const prompt=state.deck==="kanji"?"How is this read?":"Closest in meaning?";
  host.innerHTML=`
    <div class="panel">
      <div class="qtop"><span>Q${qz.i+1}/${qz.qs.length}</span><span>Score ${qz.score}</span></div>
      <div class="progress"><div style="width:${Math.round(qz.i/qz.qs.length*100)}%"></div></div>
      <p class="subnote">${prompt}</p>
      <div class="qword">${escapeHtml(q.card.f)}</div>
      <p class="qmean">${answered && q.card.m ? "= "+escapeHtml(q.card.m) : ""}</p>
      ${q.opts.map((o,i)=>{
        let cls="qopt";
        if(answered){
          if(o===q.card.b) cls+=" correct";
          else if(i===qz.picked) cls+=" wrong";
        }
        return `<button class="${cls}" data-i="${i}" ${answered?"disabled":""}>${escapeHtml(o)}</button>`;
      }).join("")}
      ${answered?`<button class="nextbtn" id="nextQ">${qz.i+1<qz.qs.length?"Next →":"See result"}</button>`:""}
    </div>`;
  document.querySelectorAll("#view-quiz .qopt").forEach(b=>b.onclick=()=>{
    if(qz.picked!==null) return;
    qz.picked=Number(b.dataset.i);
    if(q.opts[qz.picked]===q.card.b) qz.score++;
    renderQuiz();
  });
  const nx=$("#nextQ");
  if(nx) nx.onclick=()=>{
    qz.i++; qz.picked=null;
    if(qz.i>=qz.qs.length) qz.finished=true;
    renderQuiz();
  };
}

/* ================= view switch & theme ================= */
function renderView(){
  $("#view-review").hidden = state.view!=="review";
  $("#view-cards").hidden  = state.view!=="cards";
  $("#view-quiz").hidden   = state.view!=="quiz";
  if(state.view==="review") renderReview();
  if(state.view==="cards"){ state.order=[]; renderCards(); }
  if(state.view==="quiz"){ state.quiz=null; renderQuiz(); }
  window.scrollTo({top:0});
}
function applyTheme(t){
  document.documentElement.dataset.theme=t;
  document.querySelector('meta[name="theme-color"]').content = t==="dark"?"#111318":"#ffffff";
  store.set("jlpt.theme",t);
}
$("#themeBtn").onclick=()=>{
  applyTheme(document.documentElement.dataset.theme==="dark"?"light":"dark");
};

/* ================= boot ================= */
applyTheme(store.get("jlpt.theme", matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"));
document.documentElement.style.setProperty("--accent",LEVEL_COLORS[state.level]);
document.documentElement.style.setProperty("--accent-soft",LEVEL_COLORS[state.level]+"22");
renderHeader();
renderView();
